server:
  port: 8010
player:
  username: khanh1
  age: 24
  address: Hanoi
  maps: { k1:v1, k2:v2, k3:v3 }

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:sqlserver://DESKTOP-F5BV459;instanceName=SQLEXPRESS;databaseName=AuthDb;encrypt=false;trustServerCertificate=true
    username: sa
    password: khanh123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database: sql_server
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true