server:
  port: 8014
database:
  url: jdbc:mysql://localhost:3306/mydb
  username: user
  password: pass
player:
  username: khanh
  age: 24
  address: Hanoi
  maps: { k1:v1, k2:v2, k3:v3 }
  lists:
    - item1
    - item2
    - item3
  birthday: 1999-12-31
